apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: events-deploy
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: events-deploy
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 20.2.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/values/values-prod.yaml
    - repoURL: "https://github.com/yzhelezko/k8s.git"
      targetRevision: main
      ref: values
  destination:
    namespace: prom
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
