apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: events-deploy
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: events-deploy
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.10.1
    helm:
      releaseName: prometheus
      path: base
      valueFiles:
        - ../values/values-prod.yaml
  destination:
    namespace: prom
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
